executable		= /Users/skku_server/eic/simulation_parallel.sh
arguments		= "15 ./benchmark_240420_202113/gen/gen_15.hepmc ./benchmark_240420_202113/sim/sim_15.edm4hep.root ./benchmark_240420_202113/rec/rec_15.root"

should_transfer_files	= IF_NEEDED
when_to_transfer_output	= ON_EXIT

initialdir		= /Users/skku_server/eic/detector_benchmarks/benchmark_240420_202113/job_16

request_cpus	= 1
request_memory	= 1536M
request_disk	= 512M

#num_retries	= 2
output		= out.txt
log		= log.txt
error		= err.txt

queue 
